User.create!(name: "管理者",
             email: "kame@email.com",
             password: "000",
             password_confirmation: "000",
             admin: true)
User.create!(name: "つとむさん",
             email: "tutomu@email.com",
             password: "000",
             password_confirmation: "000",
             admin: true)
User.create!(name: "きだ",
             email: "kida@email.com",
             password: "000",
             password_confirmation: "000",
             admin: true)
